FROM node:18-alpine

WORKDIR /app

# Copier les fichiers de dépendances
COPY front/package*.json ./

# Installer les dépendances
RUN npm install

# Codes
COPY front/src/ ./src/
COPY front/public/ ./public/
COPY front/metrics-server.js ./

EXPOSE 3000
EXPOSE 9091

CMD ["sh", "-c", "node metrics-server.js & npm start"]